#!/bin/python3

from parser import parse
from compiler import compile
from typechecking import typecheck
from pathlib import Path
from contextlib import suppress

import sys

def print_variables(variables):
    for var, obj in variables.items():
        value = (
            "[" + ", ".join(map(str, obj.value)) + "]"
            if len(obj.value) > 1
            else str(obj.value[0])
        )
        print(";", var, "=", value, ":", obj.type)

for source in sys.argv[1:]:
    source = Path(source).read_text()
    ast = parse(source)
    print_variables(typecheck(ast))
    print(compile(ast))
